//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceMP.Garage.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoliceMP.Garage.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;GarageEntry&quot;: [{
        ///		&quot;Name&quot;: &quot;Police Garage&quot;,
        ///		&quot;Description&quot;: &quot;Access Police Garage&quot;,
        ///		&quot;MarkerLocation&quot;: {
        ///			&quot;X&quot;: 458.50,
        ///			&quot;Y&quot;: -1008,
        ///			&quot;Z&quot;: 27,
        ///			&quot;Heading&quot;: 0
        ///		},
        ///		&quot;OutsideLocation&quot;: {
        ///			&quot;X&quot;: 457.20,
        ///			&quot;Y&quot;: -1012.43,
        ///			&quot;Z&quot;: 28.34,
        ///			&quot;Heading&quot;: 130
        ///		}
        ///	}],
        ///	&quot;GarageSpawns&quot;: [{
        ///			&quot;Guid&quot;: &quot;a8fbef07-4fba-45bc-b4a3-152ef60e9076&quot;,
        ///			&quot;Heading&quot;: 235,
        ///			&quot;PlayerLocation&quot;: {
        ///				&quot;X&quot;: 405.93,
        ///				&quot;Y&quot;: -978.19,
        ///				&quot;Z&quot;: -99.5,
        ///				&quot;Heading&quot;: 90
        ///			}
        ///		},
        ///		{
        ///			&quot;Guid&quot;: &quot;3fbd44df-48cc-424b-bfb8-550146 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string garage_config {
            get {
                return ResourceManager.GetString("garage_config", resourceCulture);
            }
        }
    }
}
