fx_version 'cerulean'
games { 'gta5' }
lua54 'yes'

name "Metropolitan Police Custody Suite"
author "MirrorParkStudios"

this_is_a_map "yes"
data_file 'DLC_ITYP_REQUEST' 'stream/wl_custody_ytyp.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_window.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_whiteboard.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_wand.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_sign5.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_sign4.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_sign3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_sign.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_sepura.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_safety.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_lockers.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_feet.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_doorblock.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/cell_door.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/prop_plugs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/prop_fal.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/cwpropsforall.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/prop_fex.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/wilkescustodyprops.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/police_text.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/arv_base_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/safe_door.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/prop_plo_c.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/prop_nss.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/prop_nas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/prop_divide1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_fme_bed.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_kitchen.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_livescan.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_intox.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_matress.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_cellgate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props/custody_monitor.ytyp'
dependency '/assetpacks'