// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliceMP.Data.ConsoleApp;

namespace PoliceMP.Data.ConsoleApp.Migrations
{
    [DbContext(typeof(GtaContext))]
    [Migration("20210109011009_AddPlayerName")]
    partial class AddPlayerName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PoliceMP.Data.Entities.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ConnectedAt");

                    b.Property<DateTime>("DisconnectedAt");

                    b.Property<string>("DisconnectedReason");

                    b.Property<string>("Discord");

                    b.Property<string>("IpAddress");

                    b.Property<string>("License");

                    b.Property<string>("LiveId");

                    b.Property<string>("PlayerName");

                    b.Property<int>("UserId");

                    b.Property<string>("Xbl");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("PoliceMP.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("SteamId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PoliceMP.Data.Entities.Session", b =>
                {
                    b.HasOne("PoliceMP.Data.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
