<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>PoliceMP.Core.Server.net</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
        None
    </ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <LangVersion>9</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.Core.Server" Version="1.0.5879" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoliceMP.Core.Shared\PoliceMP.Core.Shared.csproj" />
    <ProjectReference Include="..\PoliceMP.Data\PoliceMP.Data.csproj" />
    <ProjectReference Include="..\PoliceMP.Shared\PoliceMP.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Microsoft.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
