Config = {
	--[[
	List in order of least priority to highest with 
	highest priority overtaking role before it if 
	they have that discord role.
	]]--
	roleList = {
		{0, "^5[PCSO] "},
		--AUX OPS
		{693544866810167347, "^8[FLIGHT OPS] "},
		{836312179367084052, "^8[CIV] "},
		--NHS
		{755152618229072014, "^5[LAS] "},
		--LFB
		{755152624369795102, "^1[LFB] "},
		---POLICE
		{797934748185264158, "^4[PC] "},
		{709052478595006594, "^4[S.PC] "},
		{652188713857843210, "^4[SGT] "},
		{652189147708129290, "^4[INSP] "},
		{652189218868559912, "^4[C/INSP] "},
		{652189423118712887, "^4[SUPT] "},
		{652189626722680833, "^3[C/SUPT] "},
		{652189715868549130, "^9[ACC] "},
		{652191713116422145, "^4[DAC] "},
		{652191913474261034, "^9[ACC] "},
		{652192284384952330, "^9[DCC] "},
		{652192513108475904, "^8[COM] "},
		-- LFB
		{928012360948523068, "^1[LFB Borough Commander] "},
		--OTHER
		{801191272349827093, "^2[Developer] "},
		{864677599417204736, "^2[Developer] "},
		{616641490336219137, "^6[Management] "},
		{598110517478817794, "💩^6[Founder] "},
	},
	allowedColors = {},
	allowedRed = {},
	allowedEmoji = {},
	sendBlockMessages = false,
	ColorPatterns = {
		['DiscordChatRoles.Access.Donator'] = {
			['White'] = {'^0'},
			['Green'] = {'^2'},
			['Yellow'] = {'^3'},
			['Blue'] = {'^4'},
			['Light Blue'] = {'^5'},
			['Purple'] = {'^6'},
			['White'] = {'^7'},
			['Pink'] = {'^9'},
			['Police'] = {'^1', '^4'},
			['Police2'] = {'^4', '^1'},
			['Christmas'] = {'^2', '^1'},
			['Christmas2'] = {'^1', '^2'},
		},
		['DiscordChatRoles.Access.Elite'] = {
			['RainbowYGB'] = {'^3', '^2', '^4'},
			['RainbowFull'] = {'^3', '^4', '^1', '^5', '^6', '^7', '^9'},
		},
		['DiscordChatRoles.Access.Staff'] = {
			['Red'] = {'^1'},
		}
	},
	emojis = {
	      [":eyes:"] = '👀',
	  	  [":thinking:"] = '🤔',
		  [":rage:"] = '😡',
		  [":alien:"] = '👽',
		  [":nauseated_face:"] = '🤢',
		  [":innocent:"] = '😇',
		  [":sunglasses:"] = '😎',
		  [":star_struck:"] = '🤩',
		  [":nerd:"] = '🤓',
		  [":face_with_symbols_over_mouth:"] = '🤬',
		  [":joy:"] = '😂',
		  [":rofl:"] = '🤣',
		  [":face_vomiting:"] = '🤮',
		  [":cold_face:"] = '🥶',
		  [":heart_eyes:"] = '😍',
		  [":kissing_heart:"] = '😘',
		  [":smiling_imp:"] = '😈',
		  [":grin:"] = '😁',
		  [":exploding_head:"] = '🤯',
		  [":stuck_out_tongue:"] = '😛',
		  [":grimacing:"] = '😬',
		  [":scream:"] = '😱',
		  [":smiley:"] = '😃',
		  [":face_with_raised_eyebrow:"] = '🤨',
		  [":triumph:"] = '😤',
		  [":kissing:"] = '😗',
		  [":kissing_smiling_eyes:"] = '😙',
		  [":fearful:"] = '😨',
		  [":wink:"] = '😉',
		  [":smiling_face_with_3_hearts:"] = '🥰',
		  [":partying_face:"] = '🥳',
		  [":sob:"] = '😭',
		  [":thumbsup:"] = '👍',
		  [":thumbsdown:"] = '👎',
		  [":punch:"] = '👊',
		  [":pray:"] = '🙏',
		  [":face_with_monocle:"] = '🧐',
		  [":smirk:"] = '😏',
		  [":cold_sweat:"] = '😰',
		  [":disappointed_relieved:"] = '😥',
		  [":angry:"] = '😠',
		  [":relieved:"] = '😌',
		  [":worried:"] = '😟',
		  [":confused:"] = '😕',
		  [":upside_down:"] = '🙃',
		  [":clown:"] = '🤡',
		  [":mask:"] = '😷',
		  [":shushing_face:"] = '🤫',
		  [":yawning_face:"] = '🥱',
		  [":imp:"] = '👿',
		  [":lying_face:"] = '🤥',
		  [":sweat:"] = '😓',
		  [":frowning2:"] = '☹️',
		  [":pleading_face:"] = '🥺',
		  [":stuck_out_tongue_winking_eye:"] = '😜',
		  [":hugging:"] = '🤗',
		  [":no_mouth:"] = '😶',
		  [":neutral_face:"] = '😐',
		  [":flushed:"] = '😳',
		  [":rolling_eyes:"] = '🙄',
		  [":expressionless:"] = '😑',
		  [":yawning_face:"] = '🥱',
		  [":hot_face:"] = '🥵',
		  [":sneezing_face:"] = '🤧',
		  [":poop:"] = '💩',
		  [":money_mouth:"] = '🤑',
		  [":sleeping:"] = '😴',
		  [":ghost:"] = '👻',
		  [":zipper_mouth:"] = '🤐',
		  [":sweat_smile:"] = '😅',
		  [":sneezing_face:"] = '🤧',
		  [":detective:"] = '🕵️',
		  [":wave:"] = '👋',
		  ["drooling_face:"] = '🤤',
		  [":head_bandage:"] = '🤕',
		  [":cowboy:"] = '🤠',
		  [":skull:"] = '💀',
		  [":busts_in_silhouette:"] = '👥',
		  [":eye:"] = '👁️',
		  [":kiss:"] = '💋',
		  [":brain:"] = '🧠',
		  [":call_me:"] = '🤙',
		  [":man_farmer::"] = '👨‍🌾',
		  [":woman_farmer:"] = '👩‍🌾',
		  [":man_police_officer:"] = '👮‍',
		  [":woman_police_officer:"] = '👮‍',
		  [":man_raising_hand:"] = '🙋‍',
		  [":panda_face:"] = '🐼',
		  [":pig:"] = '🐷',
		  [":woozy_face:"] = '🥴',
		  ["airplane:"] = '✈️',
		  ["star2:"] = '🌟',
		  [":fire:"] = '🔥',
		  [":money_with_wings:"] = '💸',
		  [":cloud_rain:"] = '🌧️',
		  [":flying_saucer:"] = '🛸',
		  [":rocket:"] = '🚀',
		  [":gun:"] = '🔫',
		  [":tools:"] = '🛠️',
	},
}