using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
// ReSharper disable InconsistentNaming

namespace PoliceMP.Shared.Models
{
    public enum PmpBlipColor
    {
        White = 0,
        Red = 1,
        Green_RedEnemy_BlueFriendly = 2,
        BlueNeutral_RedEnemy = 3,
        WhiteNeutral_RedEnemy_BlueFriendly = 4,
        YellowNeutral_RedEnemy_BlueFriendly = 5,
        LightRed = 6,
        Violet = 7,
        Pink = 8,
        LightOrange = 9,
        LightBrown = 10,
        LightGreen = 11,
        LightBlue = 12,
        LightPurple = 13,
        DarkPurple = 14,
        Cyan = 15,
        LightYellow = 16,
        Orange = 17,
        LightBlue2 = 18,
        DarkPink = 19,
        DarkYellow = 20,
        DarkOrange = 21,
        LightGray = 22,
        LightPink = 23,
        LemonGreen = 24,
        ForestGreen = 25,
        ElectricBlue = 26,
        BrightPurple = 27,
        DarkYellow2 = 28,
        DarkBlue = 29,
        DarkCyan = 30,
        LightBrown2 = 31,
        LightBlue3 = 32,
        LightYellow2 = 33,
        LightPink2 = 34,
        LightRed2 = 35,
        Beige = 36,
        White2 = 37,
        Blue = 38,
        Gray = 39,
        DarkGray = 40,
        PinkRed = 41,
        Blue2 = 42,
        LightGreen2 = 43,
        LightOrange2 = 44,
        White3 = 45,
        Gold = 46,
        BrightOrange = 47,
        BrilliantRose = 48,
        RedNeutral_BlueFriendly = 49,
        MediumPurple = 50,
        Salmon = 51,
        DarkGreen = 52,
        BlizzardBlue = 53,
        OracleBlue = 54,
        Silver = 55,
        Brown = 56,
        Blue3 = 57,
        EastBay = 58,
        Red2 = 59,
        YellowOrange = 60,
        MulberryPink = 61,
        AltoGray = 62,
        JellyBeanBlue = 63,
        DarkOrange2 = 64,
        Mamba = 65,
        YellowOrangeNeutral_RedEnemy_BlueFriendly = 66,
        BlueNeutral_RedEnemy2 = 67,
        BlueNeutral_RedEnemy3 = 68,
        GreenNeutral_RedEnemy_BlueFriendly = 69,
        YellowOrange2 = 70,
        YellowOrange3 = 71,
        TransparentBlack = 72,
        YellowOrange4 = 73,
        Blue4 = 74,
        Red3 = 75,
        DeepRed = 76,
        Blue5 = 77,
        OracleBlue2 = 78,
        TransparentRed = 79,
        TransparentBlue = 80,
        Orange2 = 81,
        LightGreen3 = 82,
        Purple = 83,
        Blue6 = 84,
        TransparentBlack2 = 85
    }
}
