function AddTextEntry(GetHashKey(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

--[[
Citizen.CreateThread(function()
	AddTextEntry(GetHashKey("0x7804F199"), "Volkswagen Touran")
	AddTextEntry(GetHashKey("0xC853D516"), "Dog Van")
	AddTextEntry(GetHashKey("0x328078FD"), "Audi Avant")
	AddTextEntry(GetHashKey("0x78636A02"), "Road Incident Vehicle")
	AddTextEntry(GetHashKey("0xCA89D0C3"), "Volkswagen Golf")
	AddTextEntry(GetHashKey("0x489DAEB9"), "Ford Kuga")
	AddTextEntry(GetHashKey("0xD7E4F078"), "Ford Kuga")
	AddTextEntry(GetHashKey("0xD64A79BE"), "Ford Focus")
	AddTextEntry(GetHashKey("0x23D5EE4A"), "Ford Focus")
	AddTextEntry(GetHashKey("0x7D9A3C19"), "Ford Mustang")
	AddTextEntry(GetHashKey("0xFA9055DB"), "BMW 1 Series")
	AddTextEntry(GetHashKey("0xA683ADC3"), "BMW 330D")
	AddTextEntry(GetHashKey("0x116FABBA"), "Land Rover Discovery")
	AddTextEntry(GetHashKey("0x2E298D74"), "Range Rover SVR")
	AddTextEntry(GetHashKey("0x7777B663"), "BMW 1 Series")
	AddTextEntry(GetHashKey("0x97DEB5AA"), "Audi S3")
	AddTextEntry(GetHashKey("0x8A570C77"), "Audi S3")
	AddTextEntry(GetHashKey("0xA2EF4E17"), "Vauxhall Astra")
	AddTextEntry(GetHashKey("0xCF1C80FB"), "Volkswagen Golf")
	AddTextEntry(GetHashKey("0xE76E1F96"), "Volvo V90")
	AddTextEntry(GetHashKey("0xEB8E046D"), "Volvo V90")
	AddTextEntry(GetHashKey("0xAD538FDD"), "Volvo XC90")
	AddTextEntry(GetHashKey("0x08BAFBF3"), "Ford Transit")
	AddTextEntry(GetHashKey("0x6EE6D61E"), "Mercedes Sprinter")
	AddTextEntry(GetHashKey("0x4AE4CFE6"), "BMW R 1200RT")
	AddTextEntry(GetHashKey("0xB68D032A"), "BMW X5")
	AddTextEntry(GetHashKey("0x38AE8F56"), "BMW X5")
	AddTextEntry(GetHashKey("0x899B9EF4"), "BMW 330D")
	AddTextEntry(GetHashKey("0x7A0AA156"), "Peugot 308")
	AddTextEntry(GetHashKey("0x101E803E"), "Jaguar XFR")
end)
]]


Citizen.CreateThread(function()
	AddTextEntry(GetHashKey("ADDPOLVWTOURAN"), "Volkswagen Touran")
	AddTextEntry(GetHashKey("ADDPOLDV"), "Dog Van")
	AddTextEntry(GetHashKey("ADDPOLAUDIA"), "Audi Avant")
	AddTextEntry(GetHashKey("ADDPOLRIV"), "Road Incident Vehicle")
	AddTextEntry(GetHashKey("ADDPOLVWG"), "Volkswagen Golf")
	AddTextEntry(GetHashKey("ADDPOLFORDKUM"), "Ford Kuga")
	AddTextEntry(GetHashKey("ADDPOLFORDKM"), "Ford Kuga")
	AddTextEntry(GetHashKey("ADDPOLFORDFEM"), "Ford Focus")
	AddTextEntry(GetHashKey("ADDPOLFORDFEUM"), "Ford Focus")
	AddTextEntry(GetHashKey("addpolmust"), "Ford Mustang")
	AddTextEntry(GetHashKey("addpolumbmw1"), "BMW 1 Series")
	AddTextEntry(GetHashKey("addpolumbmw2"), "BMW 330D")
	AddTextEntry(GetHashKey("addpoldisco"), "Land Rover Discovery")
	AddTextEntry(GetHashKey("addpolrrsvr"), "Range Rover SVR")
	AddTextEntry(GetHashKey("addpolbmw1s"), "BMW 1 Series")
	AddTextEntry(GetHashKey("addpolaudis3um"), "Audi S3")
	AddTextEntry(GetHashKey("addpolaudis3m"), "Audi S3")
	AddTextEntry(GetHashKey("addpolastra"), "Vauxhall Astra")
	AddTextEntry(GetHashKey("addpolvwg"), "Volkswagen Golf")
	AddTextEntry(GetHashKey("addpolvolm"), "Volvo V90")
	AddTextEntry(GetHashKey("addpolvolum"), "Volvo V90")
	AddTextEntry(GetHashKey("addpolvolxc"), "Volvo XC90")
	AddTextEntry(GetHashKey("addpolfordt"), "Ford Transit")
	AddTextEntry(GetHashKey("addpolmerc"), "Mercedes Sprinter")
	AddTextEntry(GetHashKey("addpolbmwbike"), "myName")
	AddTextEntry(GetHashKey("addpolx5m"), "BMW X5")
	AddTextEntry(GetHashKey("addpolx5um"), "BMW X5")
	AddTextEntry(GetHashKey("addpolbme"), "BMW 330D")
	AddTextEntry(GetHashKey("addpolpug"), "Peugot 308")
	AddTextEntry(GetHashKey("addpoljag"), "Jaguar XFR")
	AddTextEntry(GetHashKey("addpolbmw5arv"), "BMW 5 Series G31 ARV")
end)

