<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>9</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.15" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoliceMP.Core.Server\PoliceMP.Core.Server.csproj" />
    <ProjectReference Include="..\PoliceMP.Core.Shared\PoliceMP.Core.Shared.csproj" />
  </ItemGroup>

</Project>
